server:
  port: 8082 
        
spring:
  mail:
    host: smtp.gmail.com
    username: rh.control.mail@gmail.com
    password: hoeqqyjxirlqsqbn
    port: 587
    properties:
      mail:
        smtp:
          timeout: 60000
          connectiontimeout: 60000
          socketFactory: javax.net.ssl.SSLSocketFactory
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false
  kafka:
    producer:
      bootstrap-servers: localhost:29092

